var SPEAKERS = {
  "speakers": [
    {
      id: 'matt',
      name: 'Matt Mullenweg',
      twitter: '',
      bio: 'Lorem ipsum',
      photo: 'images/photos/speakers/matt_mullenweg.jpg',
      title: '',
      abstract: '',
      video: '',
      slides: '',
      schedule: '',
      color: 'blue'
    },
    {
      id: 'jill',
      name: 'Jill Jubinski',
      twitter: '',
      bio: 'Lorem ipsum',
      photo: 'images/photos/speakers/jill_jubinski.jpg',
      title: '',
      abstract: '',
      video: '',
      slides: '',
      schedule: '',
      color: '#dc3545'
    },
    {
      id: 'dizzy',
      name: 'Dave "Dizzy" Smith',
      twitter: '',
      bio: 'Lorem ipsum',
      photo: 'images/photos/speakers/dave_smith.jpg',
      title: '',
      abstract: '',
      video: '',
      slides: '',
      schedule: '',
      color: '#ffc107'
    },
    {
      id: 'cate',
      name: 'Cate Huston',
      twitter: '',
      bio: 'Lorem ipsum',
      photo: 'images/photos/speakers/cate_huston.jpg',
      title: '',
      abstract: '',
      video: '',
      slides: '',
      schedule: '',
      color: 'purple'
    },
    {
      id: 'valentine',
      name: 'Valentine Reid',
      twitter: '',
      bio: 'Valentine has more than ten years of experience in Information Technology with a combination of system administration, information security, business analytics, management, and compliance. His experience has been focused in heavy industry, energy, cyber security, and most recently healthcare. He has been a full time remote worker/manager since mid 2017.</br></br>Currently he lives full time in a 30 foot 5th wheel RV with his wife and three cats. They spend their time mostly south of Interstate 40 where they chase warm sunny weather on beaches, hikes in mountains, and camp fires. In his spare time he rambles about information security topics on  twitter and on his blog.',
      photo: 'images/photos/speakers/valentine_reid.jpg',
      title: '',
      abstract: '',
      video: '',
      slides: '',
      schedule: '',
      color: 'green'
    },
    {
      id: 'michael',
      name: 'Michael Stahnke',
      twitter: '',
      bio: 'Michael Stahnke is Director of Engineering overseeing Platform and Site Reliability at Puppet, Inc. He\'s held a few roles there, and been a part of the company growing from 35 to 530+ employees. While staying near the domains of release engineering, operations, and community, he\’s been in leadership for most of the last decade. His primary joy comes from building teams,  mentoring team members, and, just recently, playing Hot Wheels cars with his son. He came to Puppet from Caterpillar, Inc. where he was an infrastructure architect, system administration team lead, and open source evangelist. Michael also helped get the Extra Packages for Enterprise Linux (EPEL) repository off the ground in 2005, is the author of Pro OpenSSH (Apress, 2005), and rants with some frequency about technology and computers, while striving to learn more about them. @stahnma on twitter and medium.',
      photo: 'images/photos/speakers/michael_stahnke.jpg',
      title: '',
      abstract: '',
      video: '',
      slides: '',
      schedule: '',
      color: 'green'
    },
    {
      id: 'jameson',
      name: 'Jameson Hampton',
      twitter: '',
      bio: 'Jamey is a non-binary adventurer from Buffalo, NY who wishes they were immortal so they’d have time to visit every coffee shop in the world. They’re an artist who turned into a programmer after one too many animation classes that were computer science classes in disguise. Currently they’re working as a professional plant-liker (and software engineer) for Agrilyst, a data analysis platform for indoor agriculture. They’re also the zine librarian at Sugar City Art Collaborative and a permanent panelist on the podcast Greater Than Code. They spend most of their free time camping and thinking about Star Wars, often even at the same time.',
      photo: 'images/photos/speakers/jameson_hampton.jpg',
      title: '',
      abstract: '',
      video: '',
      slides: '',
      schedule: '',
      color: 'green'
    },
    {
      id: 'davide',
      name: 'Davide Casali',
      twitter: '',
      bio: 'Lorem ipsum',
      photo: 'images/photos/speakers/davide_casali.jpg',
      title: '',
      abstract: '',
      video: '',
      slides: '',
      schedule: '',
      color: 'green'
    },
    {
      id: 'leah',
      name: 'Leah Sutton',
      twitter: '',
      bio: 'Lorem ipsum',
      photo: 'images/photos/speakers/leah_sutton.jpg',
      title: '',
      abstract: '',
      video: '',
      slides: '',
      schedule: '',
      color: 'green'
    },
    {
      id: 'mo',
      name: 'Mo McKibbin',
      twitter: '',
      bio: 'Lorem ipsum',
      photo: 'images/photos/speakers/mo_mckibbin.jpg',
      title: '',
      abstract: '',
      video: '',
      slides: '',
      schedule: '',
      color: 'green'
    },
    {
      id: 'seth',
      name: 'Seth Thomas',
      twitter: '',
      bio: 'Lorem ipsum',
      photo: 'images/photos/speakers/seth_thomas.jpg',
      title: '',
      abstract: '',
      video: '',
      slides: '',
      schedule: '',
      color: 'green'
    },
    {
      id: 'steve',
      name: 'Steve Berry',
      twitter: '',
      bio: 'Steve Berry is the founder of Thought Merchants, a design agency in Venice Beach California. Thought Merchants brings user experience leadership to emerging companies like Casper, Harry’s, Riot Games, Hornet, and Code Climate.',
      photo: 'images/photos/speakers/steve_berry.jpg',
      title: '',
      abstract: '',
      video: '',
      slides: '',
      schedule: '',
      color: 'green'
    },
    {
      id: 'liene',
      name: 'Liene Verzemnieks',
      twitter: '',
      bio: 'Lorem ipsum',
      photo: 'images/photos/speakers/liene_verzemnieks.jpg',
      title: '',
      abstract: '',
      video: '',
      slides: '',
      schedule: '',
      color: 'green'
    },
    {
      id: 'laura',
      name: 'Laura Ellena',
      twitter: '',
      bio: 'Lorem ipsum',
      photo: 'images/photos/speakers/laura_ellena.jpg',
      title: '',
      abstract: '',
      video: '',
      slides: '',
      schedule: '',
      color: 'green'
    },
    {
      id: 'carolyn',
      name: 'Carolyn Williams',
      twitter: '',
      bio: 'Lorem ipsum',
      photo: 'images/photos/speakers/carolyn_williams.jpg',
      title: '',
      abstract: '',
      video: '',
      slides: '',
      schedule: '',
      color: 'green'
    },
    {
      id: 'karla',
      name: 'Karla Burnett',
      twitter: '',
      bio: 'Lorem ipsum',
      photo: 'images/photos/speakers/karla_burnett.jpg',
      title: '',
      abstract: '',
      video: '',
      slides: '',
      schedule: '',
      color: 'green'
    },
    {
      id: 'lorinda',
      name: 'Lorinda M. Brandon',
      twitter: '',
      bio: 'Lorem ipsum',
      photo: 'images/photos/speakers/lorinda_brandon.jpg',
      title: '',
      abstract: '',
      video: '',
      slides: '',
      schedule: '',
      color: 'green'
    },
    {
      id: 'suyog',
      name: 'Suyog Rao',
      twitter: '',
      bio: 'Suyog Rao is a Director of Engineering at Elastic, where he leads the backend teams for Elastic\'s Cloud offering. Previously, he was responsible for managing the Logstash development team and shipped many new features in multiple releases. While he is based out of San Francisco, he enjoys the distributed work culture of Elastic by traveling and working from different parts of the world.',
      photo: 'images/photos/speakers/suyog_rao.jpg',
      title: '',
      abstract: '',
      video: '',
      slides: '',
      schedule: '',
      color: 'green'
    },
  ]
};
