var SPEAKERS = {
  "speakers": [
    /* {
      id: 'matt',
      name: 'Matt Mullenweg',
      company: 'Automattic',
      twitter: '',
      bio: "Matt Mullenweg is the co-founder of the open-source blogging platform, WordPress, the most popular publishing platform on the web, and the founder & CEO of Automattic, the company behind WordPress.com, WooCommerce, and Jetpack. Additionally, Matt runs Audrey Capital, an investment and research company.",
      photo: 'images/photos/speakers/matt_mullenweg.jpg',
      title: 'Abstract',
      abstract: 'Coming Soon',
      video: '',
      slides: '',
      schedule: '',
      color: '#0d2950'
    }, */
    {
      id: 'jill',
      name: 'Jill Jubinski',
      company: 'Fastly',
      twitter: '',
      bio: "Jill Jubinski is a spirited Recruiting Leader with over 7 years experience in the technical recruiting field. She received her Masters in Industrial/Organizational Psychology with plans to change the way organizations treated their employees. When that didn’t work out she started recruiting :wink:. Jill's main priorities in her work are the humans she interacts with and the relationships being built. She strongly believes that recruiters are a strategic/impactful arm to any organization and that the work they do matters. Jill is also known to chat incessantly about her dogs, give hugs like they are going out of style and feels lucky to work at a company (Fastly) where she can be based in her hometown of St. Louis, MO.",
      photo: 'images/photos/speakers/jill_jubinski.jpg',
      title: 'Abstract',
      abstract: 'Coming Soon',
      video: '',
      slides: '',
      schedule: '',
      color: '#dc3545'
    },
    {
      id: 'dizzy',
      name: 'Dave "Dizzy" Smith',
      company: 'DigitalOcean',
      twitter: '',
      bio: "Dave &quot;Dizzy&quot; Smith is the director of cloud engineering at DigitalOcean. A software industry veteran with over 19 years of experience, Dizzy has the rare ability to breath life into abstract and theoretical business concepts with practical software solutions. He has a broad range of experience across real-time messaging systems, identity federation and authentication, and low-latency peer-to-peer data stores and has been an active contributor to many open source projects. Previously, he was VP of engineering at several database-related startups, including Basho, where he spearheaded the Rebar Project, created Bitcask, grew the engineering team from 4 to 30, and won the Erlang User of the Year Award. He was also one of the original contributors to the Jabber/XMPP project, contributing servers and clients across multiple platforms.",
      photo: 'images/photos/speakers/dave_smith.jpg',
      title: 'Abstract',
      abstract: 'Coming Soon',
      video: '',
      slides: '',
      schedule: '',
      color: '#aa8000'
    },
    {
      id: 'lisa',
      name: 'Lisa Phillips',
      company: 'Fastly',
      twitter: '',
      bio: "Lisa Phillips is VP of SRE at Fastly. With 18 years of experience in internet and web technologies with emphasis on systems and database administration, architecture, engineering, and management, Lisa isn’t afraid of hard problems or scale. She brings extensive experience in implementation and management of internet services to ensure highest levels of system availability and performance globally.",
      photo: 'images/photos/speakers/lisa_phillips.jpg',
      title: 'Abstract',
      abstract: 'Coming Soon',
      video: '',
      slides: '',
      schedule: '',
      color: '#dc3545'
    },
    {
      id: 'steve',
      name: 'Steve Berry',
      company: 'Thought Merchants',
      twitter: '',
      bio: 'Steve Berry is the founder of Thought Merchants, a design agency in Venice Beach California. Thought Merchants brings user experience leadership to emerging companies like Casper, Harry’s, Riot Games, Hornet, and Code Climate.',
      photo: 'images/photos/speakers/steve_berry.jpg',
      title: 'Remote Retrospectives Rubric',
      abstract: 'Healthy retrospectives are the barometer for any successful agile team. The added hurdle of not talking face to face about emotional and interpersonal relationships only adds obstacles for distributed teams.</br></br>We outline the right retro cadence, strategy, and tools for facilitating a successful remote retrospective. We go over tactics to avoid groupthink, encourage equal participation, and how to action insights found during the retro.',
      video: '',
      slides: '',
      schedule: '',
      color: '#600b60'
    },
    {
      id: 'michael',
      name: 'Michael Stahnke',
      company: 'Puppet',
      twitter: '',
      bio: "Michael Stahnke is Director of Engineering overseeing Platform and Site Reliability at Puppet, Inc. He's held a few roles there, and been a part of the company growing from 35 to 530+ employees. While staying near the domains of release engineering, operations, and community, he’s been in leadership for most of the last decade. His primary joy comes from building teams,  mentoring team members, and, just recently, playing Hot Wheels cars with his son. He came to Puppet from Caterpillar, Inc. where he was an infrastructure architect, system administration team lead, and open source evangelist. Michael also helped get the Extra Packages for Enterprise Linux (EPEL) repository off the ground in 2005, is the author of Pro OpenSSH (Apress, 2005), and rants with some frequency about technology and computers, while striving to learn more about them. @stahnma on twitter and medium.",
      photo: 'images/photos/speakers/michael_stahnke.jpg',
      title: 'The Dark Side of Remote Management',
      abstract: "How do you manage a problem employee when they’re not in the same place as you?<ul><li>Scenario A: you’re remote</li><li>Scenario B: they’re remote</li><li>Scenario C: you’re both remote</li></ul>Spoiler alert: hope you’ve got status on at least one commercial airline carrier.</br></br>Let's talk employee management, and the difficult stuff, performance management. How do you mentor, fix, build up, or deal with people that work thousands of miles away? Sometimes we put off the difficult conversations, sometimes we assume things are getting better. How do we actually manage this?",
      video: '',
      slides: '',
      schedule: '',
      color: '#ee780c'
    },
    {
      id: 'jameson',
      name: 'Jameson Hampton',
      company: 'Agrilyst',
      twitter: '',
      bio: 'Jamey is a non-binary adventurer from Buffalo, NY who wishes they were immortal so they’d have time to visit every coffee shop in the world. They’re an artist who turned into a programmer after one too many animation classes that were computer science classes in disguise. Currently they’re working as a professional plant-liker (and software engineer) for Agrilyst, a data analysis platform for indoor agriculture. They’re also the zine librarian at Sugar City Art Collaborative and a permanent panelist on the podcast Greater Than Code. They spend most of their free time camping and thinking about Star Wars, often even at the same time.',
      photo: 'images/photos/speakers/jameson_hampton.jpg',
      title: 'Coming Out Remotely',
      abstract: 'Coming out of the closet is never an easy time - and coming out at work is often particularly intimidating leap to make, particularly for those of us who are in the process of gender transition. Luckily, many of the anxieties of coming out and transitioning in the office can be alleviated by remote work! During the process of transition, even little things like deciding what to wear or which bathroom to use can be the cause of a lot of stress and an office environment can compound those stresses. Freedom from that environment removes potential barriers regarding expression and honest communication and makes medical transition easier and more attainable.</br></br>I’d like to share my personal story about transitioning while working remotely and the pros and cons that I’ve experienced. Supporting colleagues who are transitioning is very important too and this talk will go into some ways to be a helpful and supportive ally, as a coworker or as a manager, particularly when on a distributed team. Being myself at work is a huge part of living authentically and remote work can be a huge blessing for transgender people hoping to make that leap!',
      video: '',
      slides: '',
      schedule: '',
      color: '#1d9b9e'
    },
    {
      id: 'davide',
      name: 'Davide Casali',
      company: 'Automattic',
      twitter: '',
      bio: "Davide Casali, better known as “Folletto”, is a user experience director and startup advisor. He has an hybrid background in design, psychology, business, and technology. His objective is to change for better the quality of life of the people through the products he designs and lead. He currently works for Automattic, maker of WordPress.com.",
      photo: 'images/photos/speakers/davide_casali.jpg',
      title: 'Remote Design: The Async Advantage',
      abstract: "Working remotely has many benefits but also some obvious and non-obvious challenges. Discussions about remote work also often tend to be generic, however each discipline require its own kind of variations, and design isn't different.</br></br>A lot of the tools available to designers are meant to be used in person, but what if we happen to work remotely, or we want to switch a product team to being remote? How to build trust, gather feedback and craft a unified vision? This talk takes inspiration from some of the practices of Automattic's teams to overcome some of the unique challenges of remote working.</br></br>These solutions will also be beneficial to any designer that desires to engage with open source projects, as they are by definition remote.",
      video: '',
      slides: '',
      schedule: '',
      color: '#0d2950'
    },
    {
      id: 'leah',
      name: 'Leah Sutton',
      company: 'Elastic',
      twitter: '',
      bio: 'Coming Soon',
      photo: 'images/photos/speakers/leah_sutton.jpg',
      title: 'You Look Like Me - Diversity in Distributed Teams',
      abstract: "Diversity, without question, matters immensely in any field. And yet, when managing a distributed company there is a new challenge to consider. Words carry meaning (be they positive or negative) and the meaning of 'diversity' is entirely different for Austin, Des Moines, Tokyo, Sydney, Berlin, and the woods of Slovenia.</br></br>At Elastic, we have expanded our Diversity initiatives to also focus on Inclusion and Belonging. In this session, we will explore what we have learned, success, and failure in the journey towards a more open and inclusive company.",
      video: '',
      slides: '',
      schedule: '',
      color: '#dc3545'
    },
    {
      id: 'mo',
      name: 'Mo McKibbin',
      company: 'Help Scout',
      twitter: '',
      bio: "Mo McKibbin has worked on every side of the remote work coin. From freelance odd jobs, attempted entrepreneurship, to her current role on the Growth team at the remote first company Help Scout, she's dipped her toes in digital nomading, coworking spaces, and full on pajama life. Basically, she 'gets it.' Creator of the remote lifestyle blog Remotely Crue, she's excited to share her learnings and experience with remote work newbies, nomads, and nympholepts alike.",
      photo: 'images/photos/speakers/mo_mckibbin.jpg',
      title: 'How to deal with the whole loneliness thing',
      abstract: "Not having the benefits of colocated bonding events like happy hours or lunch dates means we’re on our own for social engagements, and making friends as an adult can be damn hard. The days of finding someone wearing a Death Cab shirt and deciding to be friends are long gone. It doesn't matter if you're an introvert or an extrovert - we're social animals! We need social interaction to stay happy and healthy (yes, even you, introverts!)</br></br>Since the 50s, sociologists have agreed on three conditions crucial to making close friends: proximity; repeated, unplanned interactions; and a setting that encourages people to let their guard down and confide in eachother. Those conditions can be hard to come by as a remote worker, but not impossible.</br></br>This talk will cover ways to foster situations you can recreate these conditions and cope with one of the less attractive byproducts of remote work: loneliness.",
      video: '',
      slides: '',
      schedule: '',
      color: '#1d9b9e'
    },
    {
      id: 'seth',
      name: 'Seth Thomas',
      company: 'Chef Software',
      twitter: '',
      bio: 'Seth Thomas has been fighting with computers for over half his time on earth and happily does so now on behalf of Chef. Prior he evangelized databases at Basho, built the largest OpenLDAP system in Higher Education at the University of Texas, and made some video games for the likes of Vigil and Sony Online Entertainment. When not solving tech problems he can be found on any stretch of grass large enough for a pickup game of soccer.',
      photo: 'images/photos/speakers/seth_thomas.jpg',
      title: 'You Are Not Broken: Remote Work and Attention Deficit Disorders',
      abstract: "Remote work offers employees an incredible amount of flexibility at the cost of requiring (tremendous) self-determination. This is great for lots of people but what about those of us who suffer from attention deficit disorders? This is a personal story about my own crossover to remote work, struggling to adapt, eventual diagnosis, and accepting help for a problem I never though I had.</br></br>I want to share how these conditions can go undiagnosed, how we cope, and strategies to be happy remote workers with or without medication. Nobody should have to struggle with this alone and I'll share my story, strategies, and how I learned to love what I believed was merely my own broken brain.",
      video: '',
      slides: '',
      schedule: '',
      color: '#ee780c'
    },
    {
      id: 'karla',
      name: 'Karla Burnett',
      company: 'Stripe',
      twitter: '',
      bio: 'Coming Soon',
      photo: 'images/photos/speakers/karla_burnett.jpg',
      title: 'Always a day ahead: life as a lone engineer in APAC',
      abstract: "I’d like to chat about the experience of moving from being a local employee for a San Francisco based tech company, to being the only engineer employed by them in all of the Asia Pacific region.</br></br>I’ll cover the complexities introduced by being 18 hours ahead of your coworkers, including offset work weeks, restrictions in deploy times, and waking up to a wall of notifications. I’ll chat about how you can create buffer time in your day as a solution to these problems, as well as setting clear restrictions on your calendar, and using Google’s dual timezone functionality to your advantage.</br></br>I’ll talk about how being on such a different timezone means you end up with a more structured day, and discuss the agreements my coworkers and I have with one another, to make sure we’re able to get work done even if someone else is asleep. This ranges from when code should be reviewed by, to writing documentation, to how we think about follow the sun rotations.</br></br>Finally, I’ll mention the strange issues you run into when you have a 200ms round-trip latency to your HQ, and only have 20/1Mbps of bandwidth. This will be a mix of social problems (how do I not interrupt people?) to technical ones (how do I download dependencies locally?), with a corresponding mix of solutions. For example, saying what you meant to say, but if you realized you interrupted, ending with “sorry, you were saying ____”, or tunneling through a local AWS region to take advantage of their better cross-Pacific links.",
      video: '',
      slides: '',
      schedule: '',
      color: '#600b60'
    },
    {
      id: 'liene',
      name: 'Liene Verzemnieks',
      company: 'CircleCI',
      twitter: '',
      bio: "Liene (LEE-en-uh) Vērzemnieks is a support engineer for CircleCI, helping developers solve problems so they can build, test, and deploy with ease. Remote work challenges her to up her empathy game and enables her to attend meetings (with her cat) with teammates across the globe. She and her family live in Portland, OR, where she's a novice herbalist, decent powerlifter, and experienced high-fiver.",
      photo: 'images/photos/speakers/liene_verzemnieks.jpg',
      title: 'I Have Asyncing Feeling: Practical Empathy for Asynchronous Teams',
      abstract: 'When I transitioned to working remotely, I’d already spent three and a half years at the headquarters of a fairly remote-friendly company. I figured I’d take the lessons I’d learned, sit on the other side of the video chat, and call it good. What I hadn’t taken into account was the biggest difference between the two environments: previously, everyone I worked with was in the US...but now, my team alone spanned 17 hours’ worth of timezones. How do you work well as a team when you can’t even hop on a call at the same time?</br></br>Tools are part of it: Slack, email, and internal forums all have their place, and we’ll talk about those. Skills are another critical piece: empathy can be harder when we don’t get the real-time, non-verbal cues we’re used to, but it’s essential to help us build psychological safety and trust with our teammates. And that’s what helps us do our best work, together, no matter what time it is.</br></br>What are the pain points that can help us recognize a need for change? How can we cultivate our empathetic abilities at a distance? And how do we find opportunities to turn empathy into action? Let’s talk concrete strategies for working together when we’re rarely together.',
      video: '',
      slides: '',
      schedule: '',
      color: '#1f8536'
    },
    {
      id: 'laura',
      name: 'Laura Ellena',
      company: 'Ad Hoc',
      twitter: '',
      bio: 'Coming Soon',
      photo: 'images/photos/speakers/laura_ellena.jpg',
      title: 'Killing me Softly with Constraints: Remote UX work and Government',
      abstract: 'What happens when you add Government partnerships to the challenges of remote user experience work? This work comes with specific constraints that the team at Ad Hoc has learned to work with, in order to make remote collaboration with Government work. We’ll share our UX group’s insights on team norms and practices, ways to better communicate, and technical tools – lessons learned from our partnerships with Centers for Medicare and Medicaid Services and the Department of Veterans Affairs.</br></br>We get specific about version control and documentation when you can’t use Google docs, and pick the parts of Agile frameworks that really matter to user experience. Communication is critical – we’ll share our tips for picking the right mode of communication for different conversations, and setting expectations with stakeholders and within teams. Finally, we’ll dig in to which prototyping, communication, and documentation tools work best within the rules and regulations our Government partners need to stick to.',
      video: '',
      slides: '',
      schedule: '',
      color: '#ee780c'
    },
    {
      id: 'carolyn',
      name: 'Carolyn Williams',
      company: 'Ad Hoc',
      twitter: '',
      bio: 'Coming Soon',
      photo: 'images/photos/speakers/carolyn_williams.jpg',
      title: 'Killing me Softly with Constraints: Remote UX work and Government',
      abstract: 'What happens when you add Government partnerships to the challenges of remote user experience work? This work comes with specific constraints that the team at Ad Hoc has learned to work with, in order to make remote collaboration with Government work. We’ll share our UX group’s insights on team norms and practices, ways to better communicate, and technical tools – lessons learned from our partnerships with Centers for Medicare and Medicaid Services and the Department of Veterans Affairs.</br></br>We get specific about version control and documentation when you can’t use Google docs, and pick the parts of Agile frameworks that really matter to user experience. Communication is critical – we’ll share our tips for picking the right mode of communication for different conversations, and setting expectations with stakeholders and within teams. Finally, we’ll dig in to which prototyping, communication, and documentation tools work best within the rules and regulations our Government partners need to stick to.',
      video: '',
      slides: '',
      schedule: '',
      color: '#1d9b9e'
    },
    {
      id: 'valentine',
      name: 'Valentine Reid',
      company: '',
      twitter: '',
      bio: 'Valentine has more than ten years of experience in Information Technology with a combination of system administration, information security, business analytics, management, and compliance. His experience has been focused in heavy industry, energy, cyber security, and most recently healthcare. He has been a full time remote worker/manager since mid 2017.</br></br>Currently he lives full time in a 30 foot 5th wheel RV with his wife and three cats. They spend their time mostly south of Interstate 40 where they chase warm sunny weather on beaches, hikes in mountains, and camp fires. In his spare time he rambles about information security topics on twitter and on his blog.',
      photo: 'images/photos/speakers/valentine_reid.jpg',
      title: 'How remote can work remote be? Living in an RV, Managing a Team',
      abstract: "In this talk I'll be combining two topics, working remote in an RV, and managing a team while working remote.</br></br>The first half I'll be discussing how to succeed at working full time in an RV, including cell connectivity, the work area, sharing space with another person, and balancing travel with work without affecting productivity.</br></br>The second half of this talk will discuss managing a technical team remotely, what laid the foundation of a successful remote strategy, and why you will only succeed if your team succeeds.",
      video: '',
      slides: '',
      schedule: '',
      color: '#600b60'
    },
    {
      id: 'lorinda',
      name: 'Lorinda M. Brandon',
      company: 'Capital One',
      twitter: '',
      bio: 'Coming Soon',
      photo: 'images/photos/speakers/lorinda_brandon.jpg',
      title: 'Remote Management: building relationships and setting expectations',
      abstract: "Many of us function as a curiosity inside the enterprise - the mythical remote worker who always hesitates when asked 'where are you based?' We're exceptions to the rule, where the answer to that is not an office location but a random home office location. Imagine then that you are also a Director in the enterprise, managing teams of people who are located in standard office locations.</br></br>The importance of relationship building at an executive level is not a secret, but when you're remote, the struggle is real to build and maintain relationships not just with your team but also with all the other groups and execs in the enterprise so you can help your team overcome hurdles and get the spotlights they deserve.</br></br>This talk will talk about the challenges for remote managers, esp at an executive level, and some tips to overcome them.",
      video: '',
      slides: '',
      schedule: '',
      color: '#aa8000'
    },
    {
      id: 'suyog',
      name: 'Suyog Rao',
      company: 'Elastic',
      twitter: '',
      bio: "Suyog Rao is a Director of Engineering at Elastic, where he leads the backend teams for Elastic's Cloud offering. Previously, he was responsible for managing the Logstash development team and shipped many new features in multiple releases. While he is based out of San Francisco, he enjoys the distributed work culture of Elastic by traveling and working from different parts of the world.",
      photo: 'images/photos/speakers/suyog_rao.jpg',
      title: 'Distributed not equals to remote',
      abstract: "At Elastic we are mindful that Distributed != Remote. Many companies have a HQ and remote offices across the world. But, for us, being distributed is the norm. As a company behind popular open source software such as Elasticsearch, Logstash and Kibana we have been distributed by design, from day one, and continue to do so at scale.</br></br>In this talk, I'll present our journey from 15 engineers to 300 engineers, spread across 30+ countries and several timezones. Throughout this talk, I draw an interesting parallel between the principles of distributed systems, open source systems and how we've applied it to scale teams and software we ship. I'll talk about the communication tools and methods we've used and their evolution. I'll present our release processes, interviews, how we make decisions, and how we manage people which are all optimized for distributed work environments. There's plenty of things we tried and didn't work, so we'll talk about that as well!",
      video: '',
      slides: '',
      schedule: '',
      color: '#0d2950'
    },
  ]
};
