var SPEAKERS = {
  "speakers": [
    {
      id: 'matt',
      name: 'Matt Mullenweg',
      twitter: '',
      bio: 'Lorem ipsum',
      photo: 'images/photos/speakers/matt_mullenweg.jpg',
      title: '',
      abstract: '',
      video: '',
      slides: '',
      schedule: '',
      color: 'blue'
    },
    {
      id: 'jill',
      name: 'Jill Jubinski',
      twitter: '',
      bio: 'Lorem ipsum',
      photo: 'images/photos/speakers/jill_jubinski.jpg',
      title: '',
      abstract: '',
      video: '',
      slides: '',
      schedule: '',
      color: '#dc3545'
    },
    {
      id: 'dizzy',
      name: 'Dave "Dizzy" Smith',
      twitter: '',
      bio: 'Lorem ipsum',
      photo: 'images/photos/speakers/dave_smith.jpg',
      title: '',
      abstract: '',
      video: '',
      slides: '',
      schedule: '',
      color: '#ffc107'
    },
    {
      id: 'jill',
      name: 'Jill Jubinski',
      twitter: '',
      bio: 'Lorem ipsum',
      photo: 'images/photos/speakers/jill_jubinski.jpg',
      title: '',
      abstract: '',
      video: '',
      slides: '',
      schedule: '',
      color: 'red'
    },
    {
      id: 'jill',
      name: 'Jill Jubinski',
      twitter: '',
      bio: 'Lorem ipsum',
      photo: 'images/photos/speakers/jill_jubinski.jpg',
      title: '',
      abstract: '',
      video: '',
      slides: '',
      schedule: '',
      color: 'purple'
    },
    {
      id: 'cate',
      name: 'Cate Huston',
      twitter: '',
      bio: 'Lorem ipsum',
      photo: 'images/photos/speakers/cate_huston.jpg',
      title: '',
      abstract: '',
      video: '',
      slides: '',
      schedule: '',
      color: 'purple'
    },
    {
      id: 'cate',
      name: 'Cate Huston',
      twitter: '',
      bio: 'Lorem ipsum',
      photo: 'images/photos/speakers/cate_huston.jpg',
      title: '',
      abstract: '',
      video: '',
      slides: '',
      schedule: '',
      color: 'green'
    },
    {
      id: 'cate',
      name: 'Cate Huston',
      twitter: '',
      bio: 'Lorem ipsum',
      photo: 'images/photos/speakers/cate_huston.jpg',
      title: '',
      abstract: '',
      video: '',
      slides: '',
      schedule: '',
      color: 'green'
    },
    {
      id: 'cate',
      name: 'Cate Huston',
      twitter: '',
      bio: 'Lorem ipsum',
      photo: 'images/photos/speakers/cate_huston.jpg',
      title: '',
      abstract: '',
      video: '',
      slides: '',
      schedule: '',
      color: 'green'
    },
  ]
};
